version: "3.8"
services:
  keras-lab:
    container_name: keras-lab-container
    volumes:
      - ./notebooks:/root/notebooks
      - ./data:/root/data
      - ./models:/root/models
      - ./dataset:/root/dataset
      - ./result:/root/result
    ports:
      - '8893:8888'
    restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
      GRANT_SUDO: 'yes'
  #  command: ["start", "--privileged"]
    user:
     "root"
    build: ./
